interface DB_MOB_CATEGORIA {
    CD_CATEGORIA: number;
    DESCRICAO_CATEGORIA: string;
}

/* 
CREATE TABLE DB_MOB_CATEGORIA (
    CD_CATEGORIA         INTEGER NOT NULL,
    DESCRICAO_CATEGORIA  VARCHAR(40)
);

ALTER TABLE DB_MOB_CATEGORIA ADD CONSTRAINT PK_DB_MOB_CATEGORIA PRIMARY KEY (CD_CATEGORIA);
*/
