interface DB_MOB_REST_GARCOM {
    CD_GARCOM: string;
    NOME_GARCOM: string;
    SENHA_GARCOM: string;
    COMISSAO_GARCOM: number;
    DTA_TRANS: string,
    HORARIO_INICIO: string,
    HORARIO_FIM: string;
}

/* CREATE TABLE DB_MOB_REST_GARCOM (
    CD_GARCOM INTEGER,
    NOME_GARCOM VARCHAR(30),
    SENHA_GARCOM INTEGER,
    COMISSAO_GARCOM NUMERIC(15,2),
    DTA_TRANS DATE,
    HORARIO_INICIO DATE,
    HORARIO_FIM DATE);

 */