interface DB_MOB_MESAS {
    CD_MESA: number;
    OCUPADA: string;
    CD_PEDIDO: number;
}

/* 
CREATE TABLE DB_MOB_MESAS (
    CD_MESA INTEGER NOT NULL,
    OCUPADA VARCHAR(1),
    CD_PEDIDO INTEGER);

ALTER TABLE DB_MOB_MESAS
ADD CONSTRAINT PK_DB_MOB_MESAS
PRIMARY KEY (CD_MESA);
*/
