interface DB_MOB_PEDIDO_CABE {
    CD_PEDIDO: number;
    CD_MESA: number;
    OBS: string;
    TOTAL: number;
    FECHADO: number;
}

interface DB_MOB_PEDIDO_LANCA {
    ITEN: number;
    CD_PRODUTO: number;
    DESCRICAO_PRODUTO: string
    UNIT_PRODUTO: number;
    DESCONTO_PRODUTO: number;
    QTD_PRODUTO: number;
    TOTAL_PRODUTO: number;
    OBS_PRODUTO: number
    CD_PEDIDO: number;
}

/* 
CREATE TABLE DB_MOB_PEDIDO_CABE (
    CD_PEDIDO INTEGER NOT NULL,
    CD_MESA INTEGER,
    OBS VARCHAR(50),
    TOTAL NUMERIC(15,2),
    FECHADO INTEGER);

ALTER TABLE DB_MOB_PEDIDO_CABE
ADD CONSTRAINT PK_DB_MOB_PEDIDO_CABE
PRIMARY KEY (CD_PEDIDO);

CREATE SEQUENCE DB_MOB_PEDIDO_CABE;
*/

/* 
CREATE TABLE DB_MOB_PEDIDO_LANCA (
    ITEN INTEGER NOT NULL,
    CD_PRODUTO INTEGER,
    DESCRICAO_PRODUTO VARCHAR(50),
    UNIT_PRODUTO NUMERIC(15,2),
    DESCONTO_PRODUTO NUMERIC(15,2),
    QTD_PRODUTO INTEGER,
    TOTAL_PRODUTO NUMERIC(15,2),
    OBS_PRODUTO VARCHAR(50),
    CD_PEDIDO INTEGER);

ALTER TABLE DB_MOB_PEDIDO_LANCA
ADD CONSTRAINT PK_DB_MOB_PEDIDO_LANCA
PRIMARY KEY (ITEN);

CREATE SEQUENCE DB_MOB_PEDIDO_LANCA;
*/